import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Font configuration for the application.
 * 
 * `Geist` and `Geist_Mono` are imported from Google Fonts and
 * assigned as CSS variables for consistent typography across the app.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Global metadata configuration for the Next.js application.
 * 
 * These values define the default title and description used across all routes.
 * 
 * @type {Metadata}
 * @see https://nextjs.org/docs/app/api-reference/functions/generate-metadata
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component for the entire Next.js application.
 * 
 * This component wraps all pages and shared UI elements, 
 * ensuring that global styles and fonts are applied consistently.
 * 
 * @component
 * @param {{ children: React.ReactNode }} props - Component props.
 * @param {React.ReactNode} props.children - The child components rendered inside the layout.
 * 
 * @example
 * // Example usage in Next.js app directory:
 * export default function Layout({ children }) {
 *   return (
 *     <html lang="en">
 *       <body>{children}</body>
 *     </html>
 *   );
 * }
 * 
 * @returns {JSX.Element} The root HTML structure wrapping all pages.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
